steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'europe-west1-docker.pkg.dev/birthday-game-2026/birthday-game/birthday-game:latest'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/birthday-game-2026/birthday-game/birthday-game:latest'