export enum PlayerScreen {
    CONNECTING          = 'connecting',
    RECONNECTING        = 'reconnecting',
    DISCONNECTED        = 'disconnected',
    LOBBY_NAME          = 'lobby-name',
    LOBBY_AVATAR        = 'lobby-avatar',
    LOBBY_WAITING       = 'lobby-waiting',
    BUILDING            = 'building',
    BUILDING_SUBMITTED  = 'building-submitted',
    BUILDING_SKIPPED    = 'building-skipped',
    VOTING              = 'voting',
    VOTING_DONE         = 'voting-done',
    VOTING_ALL_DONE     = 'voting-all-done',
    RESULTS             = 'results',
    WINNER_PROMPT       = 'winner-prompt',
    WINNER_UNLOCK       = 'winner-unlock',
    NEXT_ROUND          = 'next-round',
}
