#!/usr/bin/env node
/**
 * build-sprite.mjs
 *
 * Bundles all individual SVG files from src/assets/icons/src/ into a single
 * sprite file at public/assets/sprite.svg.
 *
 * Each input file becomes one <symbol> in the sprite.  The symbol id is
 * derived from the filename (without extension), so:
 *
 *   src/assets/icons/src/sticker-eye-round.svg  →  <symbol id="sticker-eye-round">
 *   src/assets/icons/src/icon-trash.svg          →  <symbol id="icon-trash">
 *
 * The viewBox is taken directly from the <svg viewBox="…"> of the source file.
 * If a file has no viewBox, a warning is printed and "0 0 24 24" is used as fallback.
 *
 * SVGs are optimised with svgo before embedding (strokes / fills preserved,
 * ids kept so <use href="#…"> works).
 *
 * Usage:
 *   node scripts/build-sprite.mjs           # normal run
 *   node scripts/build-sprite.mjs --watch   # rebuild on file changes
 *
 * Called automatically by:
 *   - `npm run prebuild`  (before ng build)
 *   - `npm run sprite`    (manually)
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, watchFile } from 'node:fs';
import { resolve, dirname, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { optimize } from 'svgo';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SRC_DIR    = resolve(__dirname, '../public/assets/svg');
const OUT_FILE   = resolve(__dirname, '../public/assets/sprite.svg');
const WATCH_MODE = process.argv.includes('--watch');

// ── SVGO config ───────────────────────────────────────────────────────────────
// Keep structure clean but preserve what's needed for sprite use:
// - removeViewBox: false  – we need viewBox on each symbol
// - cleanupIds: false     – ids are addressed externally via <use href="#id">
const SVGO_CONFIG = {
  plugins: [
    { name: 'preset-default', params: {
        overrides: {
          removeViewBox: false,
          cleanupIds: false,
          // Don't remove hidden elements – some icons use display:none tricks
          removeHiddenElems: false,
        },
    }},
    // Remove width/height attrs – not needed inside <symbol>
    { name: 'removeAttrs', params: { attrs: ['svg:width', 'svg:height'] } },
  ],
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function extractViewBox(svgContent) {
  const m = svgContent.match(/viewBox=["']([^"']+)["']/);
  return m ? m[1] : null;
}

function stripOuterSvgTag(svgContent) {
  // Remove XML declaration if present
  let s = svgContent.replace(/<\?xml[^?]*\?>/gi, '').trim();
  // Remove outer <svg …> and </svg>
  s = s.replace(/<svg[^>]*>/i, '').replace(/<\/svg\s*>/i, '').trim();
  return s;
}

function svgFileToSymbol(filePath) {
  const id   = basename(filePath, extname(filePath));
  const raw  = readFileSync(filePath, 'utf-8');

  // Optimise with svgo
  let optimised;
  try {
    const result = optimize(raw, { ...SVGO_CONFIG, path: filePath });
    optimised = result.data;
  } catch {
    console.warn(`  ⚠  svgo failed for ${basename(filePath)}, using raw file`);
    optimised = raw;
  }

  const viewBox = extractViewBox(optimised) ?? extractViewBox(raw) ?? '0 0 24 24';
  if (!extractViewBox(optimised) && !extractViewBox(raw)) {
    console.warn(`  ⚠  No viewBox found in ${basename(filePath)} – using "0 0 24 24"`);
  }

  let inner = stripOuterSvgTag(optimised);

  // Normalize hardcoded colors so icons respond to CSS `color` / Tailwind text-* utilities.
  // stroke:#000 / stroke:#000000 / stroke:black  →  stroke:currentColor
  inner = inner
    .replace(/stroke\s*:\s*(#000000|#000|black)\b/gi, 'stroke:currentColor');

  return `  <symbol id="${id}" viewBox="${viewBox}">\n    ${inner.replace(/\n/g, '\n    ')}\n  </symbol>`;
}

// ── Main build ────────────────────────────────────────────────────────────────

function build() {
  if (!existsSync(SRC_DIR)) {
    console.error(`❌  Source directory not found: ${SRC_DIR}`);
    console.error(`   Create it and place your individual SVG files there.`);
    process.exit(1);
  }

  const svgFiles = readdirSync(SRC_DIR)
    .filter(f => extname(f).toLowerCase() === '.svg')
    .sort()
    .map(f => resolve(SRC_DIR, f));

  if (svgFiles.length === 0) {
    console.warn(`⚠  No SVG files found in ${SRC_DIR}`);
    console.warn(`   The sprite will not be regenerated.`);
    return;
  }

  console.log(`\n🎨  Building sprite from ${svgFiles.length} SVG files…`);

  const symbols = [];
  const errors  = [];

  for (const file of svgFiles) {
    try {
      symbols.push(svgFileToSymbol(file));
      console.log(`  ✓  ${basename(file)}`);
    } catch (err) {
      errors.push(basename(file));
      console.error(`  ✗  ${basename(file)}: ${err.message}`);
    }
  }

  // Group symbols by prefix for readability
  const grouped = groupByPrefix(symbols);

  const sprite = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!--`,
    `  STICKERMANIA — Auto-generated SVG Sprite`,
    `  Do NOT edit this file manually.`,
    `  Source: apps/frontend/src/assets/icons/src/*.svg`,
    `  Regenerate: npm run sprite   (or npm run build)`,
    `-->`,
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"`,
    `     style="display:none" aria-hidden="true">`,
    ``,
    ...grouped,
    ``,
    `</svg>`,
  ].join('\n');

  // Ensure output directory exists
  const outDir = dirname(OUT_FILE);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  writeFileSync(OUT_FILE, sprite, 'utf-8');

  const kb = (Buffer.byteLength(sprite, 'utf-8') / 1024).toFixed(1);
  console.log(`\n✅  Sprite written to: ${OUT_FILE}`);
  console.log(`   Symbols: ${symbols.length}  |  Size: ${kb} KB`);

  if (errors.length) {
    console.error(`\n⚠  ${errors.length} file(s) had errors: ${errors.join(', ')}`);
  }
  console.log('');
}

/**
 * Group symbols by their id prefix (part before first "-") and add comments.
 * e.g. "sticker-eye-round" → prefix "sticker"
 */
function groupByPrefix(symbols) {
  const groups = new Map();
  for (const sym of symbols) {
    const idMatch = sym.match(/id="([^"]+)"/);
    const id      = idMatch?.[1] ?? '';
    const prefix  = id.split('-')[0] ?? 'misc';
    if (!groups.has(prefix)) groups.set(prefix, []);
    groups.get(prefix).push(sym);
  }

  const lines = [];
  for (const [prefix, syms] of groups) {
    lines.push(`  <!-- ── ${prefix} ─────────────────────────────────── -->`);
    lines.push(...syms);
    lines.push('');
  }
  return lines;
}

// ── Watch mode ────────────────────────────────────────────────────────────────

if (WATCH_MODE) {
  build();
  console.log(`👁  Watching ${SRC_DIR} for changes… (Ctrl+C to stop)\n`);
  const poll = () => {
    const files = existsSync(SRC_DIR)
      ? readdirSync(SRC_DIR).filter(f => extname(f) === '.svg').map(f => resolve(SRC_DIR, f))
      : [];
    for (const f of files) {
      watchFile(f, { interval: 800 }, (curr, prev) => {
        if (curr.mtimeMs !== prev.mtimeMs) {
          console.log(`\n♻  Changed: ${basename(f)}`);
          build();
        }
      });
    }
  };
  poll();
} else {
  build();
}

